//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelMailContainer : DbContext
    {
        public ModelMailContainer()
            : base("name=ModelMailContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RegionDB> RegionDBSet { get; set; }
        public DbSet<PostManDB> PostManDBSet { get; set; }
        public DbSet<SubEditionDB> SubEditionDBSet { get; set; }
        public DbSet<SubscriberDB> SubscriberDBSet { get; set; }
    }
}
