//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostalOfficeDB
    {
        public PostalOfficeDB()
        {
            this.SubEditionDB = new HashSet<SubEditionDB>();
            this.PostManDB = new HashSet<PostManDB>();
            this.RegionDB = new HashSet<RegionDB>();
            this.SubscriberDB = new HashSet<SubscriberDB>();
        }
    
        public int Id { get; set; }
        public string TitlePostal { get; set; }
    
        public virtual ICollection<SubEditionDB> SubEditionDB { get; set; }
        public virtual ICollection<PostManDB> PostManDB { get; set; }
        public virtual ICollection<RegionDB> RegionDB { get; set; }
        public virtual ICollection<SubscriberDB> SubscriberDB { get; set; }
    }
}
