//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionDB
    {
        public RegionDB()
        {
            this.Id = 1;
            this.SubEditionDB = new HashSet<SubEditionDB>();
            this.SubscriberDB = new HashSet<SubscriberDB>();
        }
    
        public int Id { get; set; }
        public string TitleReg { get; set; }
    
        public virtual PostalOfficeDB PostalOfficeDB { get; set; }
        public virtual PostManDB PostManDB { get; set; }
        public virtual ICollection<SubEditionDB> SubEditionDB { get; set; }
        public virtual ICollection<SubscriberDB> SubscriberDB { get; set; }
    }
}
