//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubEditionDB
    {
        public SubEditionDB()
        {
            this.SubscriberDB = new HashSet<SubscriberDB>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public double Price { get; set; }
    
        public virtual ICollection<SubscriberDB> SubscriberDB { get; set; }
    }
}
